
GET http://127.0.0.1:3000/


### echo test
PATCH http://127.0.0.1:3000/echo/test
Content-Type: application/x-www-form-urlencoded
X-Test-Foo: Bar

name=test&label=bar&state[temperature]=23


### get devices
GET /devices
Host: 127.0.0.1:3000


### create device
POST /devices
Host: 127.0.0.1:3000
Content-Type: application/json

{"name": "test-01", "color": "red"}


### update device
PATCH /devices/qn1KOcULZd
Host: 127.0.0.1:3000
Content-Type: application/json

{"color": "green"}


### delete device
DELETE /devices/QIPO3Bjf01
Host: 127.0.0.1:3000