
GET http://127.0.0.1:3000/

### 01. echo test
POST http://127.0.0.1:3000/echo/test?&q1=foo&q2=bar
Content-Type: application/json
X-Test-Foo: Bar

{"x": 22}


### get devices
GET http://127.0.0.1:3000/devices

### create device
POST http://127.0.0.1:3000/devices
Content-Type: application/json

{"x": 1}

### update device
PATCH http://127.0.0.1:3000/devices/qn1KOcULZd
Content-Type: application/json

{"x": 2}

### update device
DELETE http://127.0.0.1:3000/devices/QIPO3Bjf01